# Generated by Django 5.2.6 on 2025-09-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_item_quantity_item_storage_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='code',
            field=models.IntegerField(default=None),
        ),
    ]
