# Generated by Django 5.2.6 on 2025-09-17 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_remove_item_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='owner_id',
        ),
    ]
