# Generated by Django 5.2.6 on 2025-10-12 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_item_name_alter_item_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='object',
        ),
    ]
