# Generated by Django 5.2.6 on 2025-10-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_rename_name_item_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='storage_location',
            field=models.CharField(choices=[('P1', 'Pátio 1'), ('P2', 'Pátio 2'), ('P3', 'Pátio 3'), ('A', 'Armazém')]),
        ),
    ]
