# Generated by Django 5.2.6 on 2025-10-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_alter_item_storage_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='storage_location',
            field=models.CharField(null=True),
        ),
    ]
