# Generated by Django 5.2.6 on 2025-10-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_alter_item_storage_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_available',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='object',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='storage_location',
            field=models.CharField(),
        ),
    ]
