# Generated by Django 5.2.6 on 2025-11-22 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_alter_item_description_alter_item_is_available_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
