# Generated by Django 5.2.6 on 2025-11-26 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0013_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_item', to='storage.item'),
        ),
    ]
