# Generated by Django 5.2.6 on 2025-11-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0014_transaction_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_date']},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='object_id',
        ),
    ]
