# Generated by Django 5.2.6 on 2025-11-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0015_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='was_available',
            field=models.BooleanField(default=True),
        ),
    ]
