# Generated by Django 5.2.6 on 2025-12-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0016_transaction_was_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-loan_date']},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='created_date',
            new_name='loan_date',
        ),
        migrations.AddField(
            model_name='transaction',
            name='returned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('loan', 'Loan'), ('devolution', 'Devolution')], default='loan', max_length=10),
        ),
    ]
