# Generated by Django 5.2.6 on 2025-12-29 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0020_item_borrower_item_last_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='item',
            name='last_transaction',
        ),
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item', to=settings.AUTH_USER_MODEL),
        ),
    ]
