# Generated by Django 5.2.6 on 2025-12-30 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0022_alter_item_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='current_loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_currently_assigned', to='storage.transaction'),
        ),
    ]
