# Generated by Django 5.2.6 on 2025-12-30 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0023_item_current_loan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='current_loan',
        ),
    ]
