objects = [
    "Parafuso",
    "Cimento",
    "Tijolo",
    "Areia",
    "Brita",
    "Tinta",
    "Pincel",
    "Serrote",
    "Martelo",
    "Chave de fenda",
    "Broca",
    "Cabo elétrico",
    "Tubo PVC",
    "Luva de proteção",
    "Capacete",
    "Pregos",
    "Lixa",
    "Rolo de pintura",
    "Fio de cobre",
]
